default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Rails.application.credentials.RAILS_DB_MAX_THREADS { 5 } %>
  host: localhost
  username: postgres
  password: postgres
  # host: 172.16.16.242

development:
  <<: *default
  database: thor_development

test:
  <<: *default
  database: thor_test
 

production:
  <<: *default
  database: thor_production
  

